# Funding options for this project
# You can add your funding links here when ready

# github: [Gren-95]
# ko_fi: your_username
# liberapay: your_username
# custom: ['https://www.buymeacoffee.com/yourusername']
